In [1]:
import pandas as pd
import os
from datetime import date, datetime
import csv

In [3]:
widths = [
    9, # Retiree SSN
    9, # Member SSN
    20, # Member First Name
    20, # Member Last Name
    8, # Member Date of Birth
    1, # Member Gender
    8, # Enrollment Effective Date
    8, # Enrollment Term Date
    1, # Member Relation Code
    10, # Phone Number
    40, # Address 1
    40, # Address 2
    30, # City
    2, # State
    10, # Zip Code
    60, # Email Address
    8, # Medicare A Start Date
    8, # Medicare B Start Date
    12, # Member HICN
    8, # OGB Member ID
    8, # Death Date
    8, # Divorce Date
    8, # Report Date
]

In [5]:
filename1 = r"C:\Users\tape\Desktop\Python\ODE\LouisianaOGBQualifiedFundedTimePeriods_2020-05-15.txt"
filename2 = r"C:\Users\tape\Desktop\Python\TestLouisianaDev.txt"

In [6]:
df1 = pd.read_fwf(filename1, header=None, widths=widths, dtype = "object")
df1

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,437522941,434486377,Septime,PffjSaceDev,19350515,M,20130101,NaN,1,9855420000,...,LA,70455,testextend+dev13775550@gmail.com,20000501,20000501,434486377A,00387218,NaN,NaN,20200527
1,437522941,437522941,Doris,PffjDfbjDev,19371124,F,20130101,NaN,NaN,9855420000,...,LA,70455,testextend+dev13775551@gmail.com,20021101,20021101,434486377B,00183110,NaN,NaN,20200527
2,157441353,157441353,Kathleen,PdjjKcdeDev,19510317,F,20160301,NaN,NaN,9853450000,...,LA,70401,testextend+dev14465683@gmail.com,20160301,20160301,157441353T,00004814,NaN,NaN,20200527
3,438266661,438266661,Yvonne,JebjYaejDev,19241012,F,20150101,NaN,NaN,9852290000,...,MO,65616,testextend+dev14540162@gmail.com,19891001,19891001,434163278D,00207097,NaN,NaN,20200527
4,438365088,438365088,JOELLA,WebjJdjjDev,19260624,F,20150101,NaN,NaN,5048870000,...,LA,70003,testextend+dev14540299@gmail.com,19910601,19910601,438365088A,00210208,NaN,NaN,20200527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,435907914,435907914,Vicky,BbjjVbjjDev,19511209,F,20170101,NaN,NaN,2259210000,...,LA,70817,testextend+dev17025033@gmail.com,20161201,20161201,435907914A,00715881,NaN,NaN,20200527
687,438863998,438863998,Carmen,LajjCfeeDev,19511229,F,20161201,NaN,NaN,9857730000,...,LA,70420,testextend+dev17085556@gmail.com,20161201,20161201,438863998A,00227821,NaN,NaN,20200527
688,433863432,433863432,GARY,AbejGfjjDev,19510919,M,20161001,NaN,NaN,5043880000,...,LA,70002,testextend+dev17136813@gmail.com,20160901,20160901,433863432T,00724651,NaN,NaN,20200527
689,435828376,435828376,GAYLA,SebbGdjjDev,19490110,F,20161101,NaN,NaN,2256100000,...,LA,70791,testextend+dev17156851@gmail.com,20140101,20161101,436689086D6,00126796,NaN,NaN,20200527
690,433905051,439646727,Larry,PfbjLfjjDev,19460803,M,20161101,NaN,1,2259390000,...,LA,70806,testextend+dev17196116@gmail.com,20110801,20150101,439646727A,00677630,NaN,NaN,20200527

In [7]:
df2 = pd.read_fwf(filename2, header=None, widths=widths, dtype = "object")
df2

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,437522941,434486377,Septime,PffjSaceDev,19350515,M,20130101,NaN,1,9855420000,...,LA,70455,testextend+dev13775550@gmail.com,20000501,20000501,434486377A,00387218,NaN,NaN,20200526
1,437522941,437522941,Doris,PffjDfbjDev,19371124,F,20130101,NaN,NaN,9855420000,...,LA,70455,testextend+dev13775551@gmail.com,20021101,20021101,434486377B,00183110,NaN,NaN,20200526
2,157441353,157441353,Kathleen,PdjjKcdeDev,19510317,F,20160301,NaN,NaN,9853450000,...,LA,70401,testextend+dev14465683@gmail.com,20160301,20160301,157441353T,00004814,NaN,NaN,20200526
3,438266661,438266661,Yvonne,JebjYaejDev,19241012,F,20150101,NaN,NaN,9852290000,...,MO,65616,testextend+dev14540162@gmail.com,19891001,19891001,434163278D,00207097,NaN,NaN,20200526
4,438365088,438365088,JOELLA,WebjJdjjDev,19260624,F,20150101,NaN,NaN,5048870000,...,LA,70003,testextend+dev14540299@gmail.com,19910601,19910601,438365088A,00210208,NaN,NaN,20200526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,435907914,435907914,Vicky,BbjjVbjjDev,19511209,F,20170101,NaN,NaN,2259210000,...,LA,70817,testextend+dev17025033@gmail.com,20161201,20161201,435907914A,00715881,NaN,NaN,20200526
687,438863998,438863998,Carmen,LajjCfeeDev,19511229,F,20161201,NaN,NaN,9857730000,...,LA,70420,testextend+dev17085556@gmail.com,20161201,20161201,438863998A,00227821,NaN,NaN,20200526
688,433863432,433863432,GARY,AbejGfjjDev,19510919,M,20161001,NaN,NaN,5043880000,...,LA,70002,testextend+dev17136813@gmail.com,20160901,20160901,433863432T,00724651,NaN,NaN,20200526
689,435828376,435828376,GAYLA,SebbGdjjDev,19490110,F,20161101,NaN,NaN,2256100000,...,LA,70791,testextend+dev17156851@gmail.com,20140101,20161101,436689086D6,00126796,NaN,NaN,20200526
690,433905051,439646727,Larry,PfbjLfjjDev,19460803,M,20161101,NaN,1,2259390000,...,LA,70806,testextend+dev17196116@gmail.com,20110801,20150101,439646727A,00677630,NaN,NaN,20200526

In [11]:
df2[22] = "20200527"

In [12]:
df2

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,437522941,434486377,Septime,PffjSaceDev,19350515,M,20130101,NaN,1,9855420000,...,LA,70455,testextend+dev13775550@gmail.com,20000501,20000501,434486377A,00387218,NaN,NaN,20200527
1,437522941,437522941,Doris,PffjDfbjDev,19371124,F,20130101,NaN,NaN,9855420000,...,LA,70455,testextend+dev13775551@gmail.com,20021101,20021101,434486377B,00183110,NaN,NaN,20200527
2,157441353,157441353,Kathleen,PdjjKcdeDev,19510317,F,20160301,NaN,NaN,9853450000,...,LA,70401,testextend+dev14465683@gmail.com,20160301,20160301,157441353T,00004814,NaN,NaN,20200527
3,438266661,438266661,Yvonne,JebjYaejDev,19241012,F,20150101,NaN,NaN,9852290000,...,MO,65616,testextend+dev14540162@gmail.com,19891001,19891001,434163278D,00207097,NaN,NaN,20200527
4,438365088,438365088,JOELLA,WebjJdjjDev,19260624,F,20150101,NaN,NaN,5048870000,...,LA,70003,testextend+dev14540299@gmail.com,19910601,19910601,438365088A,00210208,NaN,NaN,20200527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,435907914,435907914,Vicky,BbjjVbjjDev,19511209,F,20170101,NaN,NaN,2259210000,...,LA,70817,testextend+dev17025033@gmail.com,20161201,20161201,435907914A,00715881,NaN,NaN,20200527
687,438863998,438863998,Carmen,LajjCfeeDev,19511229,F,20161201,NaN,NaN,9857730000,...,LA,70420,testextend+dev17085556@gmail.com,20161201,20161201,438863998A,00227821,NaN,NaN,20200527
688,433863432,433863432,GARY,AbejGfjjDev,19510919,M,20161001,NaN,NaN,5043880000,...,LA,70002,testextend+dev17136813@gmail.com,20160901,20160901,433863432T,00724651,NaN,NaN,20200527
689,435828376,435828376,GAYLA,SebbGdjjDev,19490110,F,20161101,NaN,NaN,2256100000,...,LA,70791,testextend+dev17156851@gmail.com,20140101,20161101,436689086D6,00126796,NaN,NaN,20200527
690,433905051,439646727,Larry,PfbjLfjjDev,19460803,M,20161101,NaN,1,2259390000,...,LA,70806,testextend+dev17196116@gmail.com,20110801,20150101,439646727A,00677630,NaN,NaN,20200527

In [13]:
df1.equals(df2)

True